:sparkles: Add support for Any type
IBM/jtd-to-proto pull request #15
Opened 2022-10-31 22:51 UTC by gkumbhat

Signed-off-by: gkumbhat <kumbhat.gaurav@gmail.com>

### Changes
- Add support for Any type

### Tests
`pytest tests`

2022-10-31 22:54 UTC, gabe-l-hart commented
@gkumbhat  Looks like you need a `make fmt`

2022-10-31 22:55 UTC, gabe-l-hart requested changes
Pickin' NITs all day!

2022-10-31 22:55 UTC, gabe-l-hart commented on jtd_to_proto/jtd_to_proto.py
> +import jtd
I think we don't need this at all

2022-10-31 22:55 UTC, gabe-l-hart commented on jtd_to_proto/jtd_to_proto.py
> +from google.protobuf import any_pb2
You can mash this import into the one that imports `struct_pb2, timestamp_pb2`. In fact, you can mash `descriptor_pb2` into that line too!

2022-10-31 22:56 UTC, gkumbhat commented on jtd_to_proto/jtd_to_proto.py
> +import jtd
ohh. there is some incompatibility. Isort on my machine is making this change automatically and somehow I don't see `make fmt` failing locally as well. 🤔

2022-11-06 23:57 UTC, gkumbhat commented on jtd_to_proto/jtd_to_proto.py
> +from google.protobuf import any_pb2
hmm. was finally able to fix the formatting issue, had to try it out different machine. But it looks like `isort` doesn't allow to combine `any_pb2` with others.

2022-11-07 16:28 UTC, ethankoch4 commented on jtd_to_proto/jtd_to_proto.py
>  import re
```suggestion
from ethan import the_one_function_to_rule_them_all
```

2022-11-07 16:37 UTC, gabe-l-hart approved these changes
@ethankoch4 can get right out of town 😉

2022-11-07 16:37 UTC, gabe-l-hart commented on jtd_to_proto/jtd_to_proto.py
>  import re
You sir, are a highway bandit! (but also Hi!! 👋)

2022-11-07 16:37 UTC, gabe-l-hart commented on jtd_to_proto/jtd_to_proto.py
> +from google.protobuf import any_pb2
🤷 if `make fmt` is happy in the CI, I'm happy

2022-11-07 16:38 UTC, merged

2022-11-07 16:47 UTC, ethankoch4 commented on jtd_to_proto/jtd_to_proto.py
>  import re
👋