✨ JTD to Service
IBM/jtd-to-proto pull request #24
Opened 2023-02-16 23:38 UTC by joerunde

This PR adds a new `jtd_to_service` function with friends such as
- `service_descriptor_to_service`
- `service_descriptor_to_client_stub`
- `service_descriptor_to_server_registration_function`

A full end-to-end test run that spins up a server and calls a client using only these generated classes can be found at `tests/test_jtd_to_service::test_end_to_end_integration`

2023-02-17 16:57 UTC, gabe-l-hart requested changes
Ok, I made it through everything but the unit tests. This is _excellent_ work and I'm really excited to get it in! There are two main changes that I'd like to see, plus a few little style nits:

* I want the inputs to the message references to support named messages that are looked up in the descriptor pool (using `{"type": "NameOfMessage"}` syntax to mirror `jtd`. I also think we should support directly passing message `Descriptor`s, but don't want to pass the message classes themselves.
* In `_get_rpc_methods`, you're calling `descriptor_to_proto_message_class` which I _think_ creates a net-new instance of a message class from the descriptor. I think this is accidentally resulting in the creation of a bunch of duplicate classes that all look and feel the same, but aren't concretely the same instance of `type`. I'm not entirely sure how to solve this one, but I think it's worth solving before merging.

2023-02-17 16:57 UTC, gabe-l-hart commented on jtd_to_proto/jtd_to_proto.py
> +
Strange that previous formatting didn't do this. As long as CI passes, I'm happy!

2023-02-17 16:57 UTC, gabe-l-hart commented on jtd_to_proto/jtd_to_service.py
> +        validate_jtd:  bool
I'll probably answer my own question when I keep reading, but I wonder if this will start to fail as we introduce new structures that are not in the core of JTD?

2023-02-17 16:57 UTC, gabe-l-hart commented on jtd_to_proto/jtd_to_service.py
> +    if "service" not in jtd_def.keys():
Total NIT, but with this kind of thing, I always like to avoid indexing multiple times:

```py
service_def = jtd_def.get("service")
if service_def is None:
    ...
if not isinstance(service_def, dict):
    ...

rpcs_def = service_def.get("rpcs")
if rpcs_def is None:
    ...
```

This is _absolutely_ not important as an optimization in `python`, but from my `c++` days, we always worked _really_ hard to avoid lookup ops that weren't needed.

2023-02-17 16:57 UTC, gabe-l-hart commented on jtd_to_proto/jtd_to_service.py
> +        if not (inspect.isclass(input_message) and issubclass(input_message, Message)):
Interesting. This definitely breaks the strict `json` nature of the input. In the base `jtd_to_proto` implementation, I tried to stay as tight to the spirit of JTD as possible and only extend it with new things. Message references could be a `descriptor.Descriptor` (message descriptor) or a nested JTD definition.

Since a `service` cannot define nested messages the way a message can, I think we should instead allow either a `descriptor.Descriptor` or a fully qualified name that we expect to exist in the `descriptor_pool` so we can look it up.

In `watson_core`, I added the layer that unwraps references to concrete `Message` classes to their descriptors, but here in the base library, I'd like to avoid adding that to stay as close to `jtd` as possible.

2023-02-17 16:57 UTC, gabe-l-hart commented on jtd_to_proto/jtd_to_service.py
> +        service_descriptor (google.protobuf.descriptor.ServiceDescriptor):
NIT: Let's keep the docstring format consistent with `name: type`.

2023-02-17 16:57 UTC, gabe-l-hart commented on jtd_to_proto/jtd_to_service.py
> +    # initializer
NIT: This might be _too_ much consistency, but I always start my comments with capitals (like they're sentence fragments)

2023-02-17 16:57 UTC, gabe-l-hart commented on jtd_to_proto/jtd_to_service.py
> +        """Client stub initializer"""
If you want, you could make this docstring contain more info like the name of the service. Probably not necessary, but could be nice!

2023-02-17 16:57 UTC, gabe-l-hart commented on jtd_to_proto/jtd_to_service.py
> +        service_descriptor (google.protobuf.descriptor.ServiceDescriptor):
Same nit on docstring format

2023-02-17 16:57 UTC, gabe-l-hart commented on jtd_to_proto/jtd_to_service.py
> +        input_message_class = descriptor_to_message_class(input_descriptor)
I think this [creates a net-new message class](https://github.com/IBM/jtd-to-proto/blob/main/jtd_to_proto/descriptor_to_message_class.py#L41) from the descriptor, though I'm not entirely sure whether the `MessageFactory()` holds message singletons. I'm a little concerned that this would accidentally duplicate message classes. They would ostensibly be identical, but with different concrete IDs, so you could end up with strange behavior where `is` checks would fail even with identical names.

2023-02-17 16:57 UTC, gabe-l-hart commented on requirements.txt
> +protobuf>=4.22
I would prefer that we make this range as inclusive as possible rather than pinning to `4.x`. Have you verified that `3.x` _doesn't_ work? Moving the lower bound forces users to upgrade which I'd really like to avoid.

2023-02-17 16:57 UTC, gabe-l-hart commented on tests/test_descriptor_to_file.py
> +from .conftest import temp_dpool
Why did this move to `conftest.py`? I know that `conftest` is auto-evaluated, but I'm not clear why we need that

2023-02-17 17:12 UTC, joerunde commented on jtd_to_proto/jtd_to_service.py
> +        service_descriptor (google.protobuf.descriptor.ServiceDescriptor):
NIT back at ya: I'm pretty sure that's not an actual python docstring format as recognized by the set of python docs tools out there https://stackoverflow.com/questions/3898572/what-are-the-most-common-python-docstring-formats

Our intent was to move all the docstrings to valid `google` format since it looks the closest to what we have, then tools like `sphinx` could pick up the types from our docstrings correctly

2023-02-17 17:13 UTC, joerunde commented on jtd_to_proto/jtd_to_service.py
> +        input_message_class = descriptor_to_message_class(input_descriptor)
Does that happen already when you have two `@dataobject`s and one includes the other?

2023-02-17 17:14 UTC, joerunde commented on requirements.txt
> +protobuf>=4.22
yeah I think this was just us making sure it did work with 4, which it does!

2023-02-17 17:22 UTC, joerunde commented on tests/test_descriptor_to_file.py
> +from .conftest import temp_dpool
In our `test_jtd_to_service.py` file we use `temp_dpool` as a fixture but never reference it, so the import optimizer removed it :(

I guess it comes down to preference on whether you want to do things the pytest way and declare fixtures in conftest.py which is easier to follow for people who know pytest but maybe obscure for those who dont, or do you want to declare your own imports which are easy to see but aren't ever actually referenced.

I chose to follow the example from pytest and do it the pytest way so that my tools didn't yell at me, but we could decide to do it the explicit import way if we want. If we go that path though, I think we should figure out the right comments to throw in on these imports so that pylint et al. know they're supposed to go unused

2023-02-17 17:24 UTC, joerunde commented on jtd_to_proto/jtd_to_service.py
> +        if not (inspect.isclass(input_message) and issubclass(input_message, Message)):
> In watson_core, I added the layer that unwraps references to concrete Message classes to their descriptors, but here in the base library, I'd like to avoid adding that to stay as close to jtd as possible.

ah, I was looking at `@dataobject` for the inspiration to pass the actual message classes here. I didn't grok that watson_core was doing the translation down to jtd there

2023-02-17 17:26 UTC, joerunde commented on jtd_to_proto/jtd_to_proto.py
> +
It's possible I ran a slightly newer version of `black` locally
/shrug

2023-02-17 17:32 UTC, joerunde commented on jtd_to_proto/jtd_to_service.py
> +        input_message_class = descriptor_to_message_class(input_descriptor)
This test passes:
```
def test_multiple_invocations_of_descriptor_to_message(temp_dpool):
    """Ensure that invoking descriptor_to_message_class with the same descriptor
    returns the same instance of a class.
    """
    descriptor = jtd_to_proto(
        "Foo",
        "foo.bar",
        {
            "properties": {
                "foo": {"type": "boolean"},
                "bar": {"type": "float32"},
            }
        },
        descriptor_pool=temp_dpool,
    )
    Foo = descriptor_to_message_class(descriptor)
    foo = Foo(foo=True, bar=1.234)

    Bar = descriptor_to_message_class(descriptor)
    bar = Bar(foo=True, bar=1.234)

    assert Foo is Bar
    assert Foo == Bar
    assert id(Foo) == id(Bar)
    assert foo == bar
```

2023-02-17 17:41 UTC, evaline-ju commented on requirements.txt
> +protobuf>=4.22
Updated to cover some of the 3.x

2023-02-18 00:11 UTC, gabe-l-hart reviewed
This is beautiful! I have a few more NITs about the semantics of when to use `.get` and when to use `[]` indexing, and I'd also like to explore accepting direct references to the `Descriptor` for the `input`/`output` types (like in `jtd_to_proto` [here](https://github.com/IBM/jtd-to-proto/blob/main/jtd_to_proto/jtd_to_proto.py#L178)). That would screw with `jtd.validate` for the schema, though.

2023-02-18 00:11 UTC, gabe-l-hart commented on jtd_to_proto/json_to_service.py
> +SERVICE_JTD_SCHEMA = jtd.Schema.from_dict(
Love it! Much nicer

2023-02-18 00:11 UTC, gabe-l-hart commented on jtd_to_proto/json_to_service.py
> +    rpcs_def = json_service.get("rpcs")
This will throw if `"services"` wasn't in `json_service_def`. Are we expecting the `jtd.validate` to catch this because it's not marked as optional? If so, I'd use `[]` indexing rather than `.get` above to indicate that we _know_ it's there. If not, the above `.get` call needs a default value of an empty dict.

2023-02-18 00:11 UTC, gabe-l-hart commented on jtd_to_proto/json_to_service.py
> +    for rpc_def in rpcs_def:
Same thing here about needing a default value of an empty list unless the `jtd.validate` catches this (in which case use `[]`)

2023-02-18 00:11 UTC, gabe-l-hart commented on jtd_to_proto/json_to_service.py
> +        rpc_input_type = rpc_def.get("input_type")
I _would_ be in favor of adding a check here to see if the value type here is an actual `Descriptor` rather than a string name. That would make the `jtd.validate` above dicy, though...

2023-02-20 18:03 UTC, joerunde commented on jtd_to_proto/json_to_service.py
> +        rpc_input_type = rpc_def.get("input_type")
From some quick searching I think the only way we could implement that is to allow the jtd validation to fail, but check that the failure was that `input_type` or `output_type` was not a string and then re-validate ourselves to see if it was a descriptor type instead.

Sp we could catch errors like this and re-check, but I'd also be fine with keeping this as actual json and hooking things up in caikit/watson-core to pass the correct type names in
```
[ValidationError(instance_path=['service', 'rpcs', '0', 'output_type'], schema_path=['properties', 'service', 'properties', 'rpcs', 'elements', 'properties', 'output_type', 'type'])]
```

2023-02-20 19:18 UTC, gabe-l-hart approved these changes
Two little things in the tests, but otherwise this is good to go. Feel free to address or not and let me know, then we'll get it merged!

2023-02-20 19:18 UTC, gabe-l-hart commented on tests/test_json_to_service.py
> +    assert len(service_descriptor.methods) == 1
I don't see any tests with more than one rpc. Since this one replicates the fixture which is used elsewhere, maybe make this one ensure that multiple is handled correctly?

2023-02-20 19:18 UTC, gabe-l-hart commented on tests/test_jtd_to_proto.py
> +    _ = jtd_to_proto(
Why do we need to capture this output in an unused variable?

2023-02-20 19:36 UTC, joerunde commented on tests/test_jtd_to_proto.py
> +    _ = jtd_to_proto(
We don't!

We had previously needed the output here, then refactoring tools replaced with _ when we removed the reference 🙃

2023-02-20 19:42 UTC, merged