Fix message collision check
IBM/jtd-to-proto pull request #29
Opened 2023-02-24 18:52 UTC by alex-jw-brooks

There are some problems in the way that we check our messages when registering things into the descriptor pool. This PR addresses them by building and comparing `FileDescriptorProto` objects for the potential conflict. More details provided in summary of changes!

### Sample Repro Case
The serialized content for the same proto objects is not always consistent. Depending on how things are created & where they are validated things like `type_name` may not be fully qualified, and for some (mysterious) reason, there are false collision errors when nested types are used.

A simple repro case for the latter is outlined below:

Happy - no nested messages
```python3
from jtd_to_proto import jtd_to_proto

msg_name = "Foo"
package = "foo.bar"
schema = {"properties": {"foo": {"type": "boolean"}}}
jtd_to_proto(msg_name,package, schema)
# Registration with the descriptor pool is idempotent, which is expected
jtd_to_proto(msg_name,package, schema)
```

Not happy; raises `ValueError: Cannot add new file foo.proto to descriptor pool, file already exists with different content`
```python3
from jtd_to_proto import jtd_to_proto

msg_name = "Foo"
package = "foo.bar"
schema = {"properties": {"foo": {"properties": {"bar": {"type": "boolean"}}}}}
jtd_to_proto(msg_name,package, schema)
# Breaks unexpectedly
jtd_to_proto(msg_name,package, schema)
```
Note that this case is handled in `test_jtd_to_proto_duplicate_message`. 

### Summary of Changes
Two FileDescriptors are considered equal if their protos satisfy the following:
- They have the same package
- They have the same dependency
- All of their enums are well-aligned, i.e., they have the same `enum_type` names, and for any/all of those, every enum val/number lines up correctly
- All of their messages are well-aligned, i.e., they have the same `message_type` names, and for each message, every field has the same `label`, `type`, and `type_name`. For the last one, we provide some flexibility in case we're comparing something that isn't fully qualified to something that is

2023-02-24 19:17 UTC, joerunde commented on jtd_to_proto/jtd_to_proto.py
> +    )
would this give a false match for e.g.
```
_have_same_type_name(".foo.bar.baz.Buzz", "bar.baz.Buzz")
```
Since the first name starts with ".", ends with the second name, and the second does not start with "."?

We could `lstrip(".")` off both and check equality? Or assert that `abs(len(d1_type_name) - len(d2_type_name)) <= 1`?

2023-02-24 19:21 UTC, joerunde commented on tests/test_jtd_to_proto.py
> +    assert _have_same_type_name(".foo.bar.Foo", "Foo")
🤔 related to the other comment, should we say that these are the same type? WOrth talkin in poerson about to get your context

2023-02-24 20:29 UTC, alex-jw-brooks commented on jtd_to_proto/jtd_to_proto.py
> +    )
Fair point - it's not just starting `Foo` vs `.Foo`. I _think_ the fully qualified path ends up as

`<package name>.<Message name>.<Field name>`

Once it's been normalized. For example, if you have something like this:

```
from jtd_to_proto import jtd_to_proto

msg_name = "Message"
package = "package"
schema = {
    "properties": {
        "field": {"properties": {"another_field": {"type": "boolean"}}},
    }
}

descriptor = jtd_to_proto(
    msg_name,
    package,
    schema,
    validate_jtd=True,
)

descriptor = jtd_to_proto(
    msg_name,
    package,
    schema,
    validate_jtd=True,
)
```

and have it drop the things it's comparing here out, it's the raw field name against the package + message + field name. I.e,. `Field` vs. `.package.Message.Field`.

We definitely could tighten this to take the package name & message name as an arg so that the fully qualified path is more predictable, but probably would want an extra test to make sure this is safe when the field is a message declared in another package. What do you think?

2023-02-27 20:33 UTC, gabe-l-hart requested changes
This is a much nicer solution (though unfortunate that it requires so much code!). I've got a couple of nits, but the main thing to fix is support for nested enums inside of messages. Otherwise it looks great

2023-02-27 20:33 UTC, gabe-l-hart commented on jtd_to_proto/jtd_to_proto.py
> +    if d1.nested_type or d2.nested_type:
We also need to check nested enums. I think that should be pretty straightforward to reuse the enum comparison above.

2023-02-27 21:22 UTC, alex-jw-brooks commented on jtd_to_proto/jtd_to_proto.py
> +        assert len(d1_enum_descriptor.value) == len(d2_enum_descriptor.value)
Ah, nice catch - this is not supposed to be an assert; it should just be a `return False` since different lengths -> different enums -> different file descriptors

2023-02-27 22:07 UTC, alex-jw-brooks commented on jtd_to_proto/jtd_to_proto.py
> +    if d1.nested_type or d2.nested_type:
Yup! Good catch, since `.enum_type` is just holding an iterable of EnumDescriptorProtos for both message descriptor protos & file descriptor protos, we can do it the same way. Made the change & added a test which previously was a failing case

2023-02-28 18:27 UTC, alex-jw-brooks commented on jtd_to_proto/jtd_to_proto.py
> +    )
Marking this as resolved, since we discussed this in person and decided to drop the extra `type_name` stuff, since it's more restrictive than anything and may lead to some false positives

2023-02-28 18:27 UTC, alex-jw-brooks commented on jtd_to_proto/jtd_to_proto.py
> +    1. the messages contained in each FileDescriptorProto are the same.
Done!

2023-02-28 18:28 UTC, alex-jw-brooks commented on jtd_to_proto/jtd_to_proto.py
> +    # For every encapsulated message descriptor, ensure that ever field has the same
Done!

2023-02-28 18:28 UTC, alex-jw-brooks commented on tests/test_jtd_to_proto.py
> +    second_enum_values = ["Hi", "Planet"]
Good call - added another test for this

2023-02-28 18:32 UTC, alex-jw-brooks commented on tests/test_jtd_to_proto.py
> +
There are some gorpy edge cases that can come out of this that we talked about in person, mostly centered around file names / not being able to look things up easily in the descriptor pool based if something is compiled with conflicting defs via protoc in a file that's different from what JTD to Proto expects internally based on message name.

For now, I added a happy path test and several other sad path tests for some of grosser corners to ensure that things fail in the right ways in a way that matches the version of `protobuf` we are using. To avoid adding protoc to the dev environment, I just added the compiled bytes + registration to the descriptor pool calls to the tests directly, but let me know if you'd prefer to add protoc and compiled the .proto files as part of the dev environment instead

2023-02-28 18:44 UTC, gabe-l-hart approved these changes
Ship it! Thanks Alex

2023-02-28 18:44 UTC, gabe-l-hart commented on tests/test_jtd_to_proto.py
> +
Sounds good!

2023-02-28 23:50 UTC, merged